import type { License } from "$lib/types";

// Maps a stored source-site id to a readable marketplace name.
const MARKETPLACES: Record<string, string> = {
  appsumo: "AppSumo",
  producthunt: "Product Hunt",
  stacksocial: "StackSocial",
  humblebundle: "Humble Bundle",
};

function marketplace(license: License): string {
  const site = license.source_site?.toLowerCase() ?? "";
  return MARKETPLACES[site] ?? license.source_site ?? "Not recorded";
}

function value(
  v: string | null | undefined,
  fallback = "Not recorded",
): string {
  return v && v.trim().length > 0 ? v : fallback;
}

/**
 * Builds a comprehensive, structured dossier for one license as Markdown.
 * Identification and maintenance sections are filled from the vault record; the
 * analytical sections (categorization, features, best use cases) are an
 * exhaustive framework to complete, since Perpetua is offline and does not fetch
 * third-party product data.
 */
export function buildDossier(license: License): {
  filename: string;
  content: string;
} {
  const today = new Date().toISOString().slice(0, 10);
  const name = license.product_name;
  const slug =
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "license";

  const keepalive =
    license.keepalive_days != null
      ? `Log in at least every ${license.keepalive_days} days`
      : "Not tracked";
  const lastUsed = value(license.last_active, "Never recorded");
  const action = license.action_required
    ? value(license.action_description, "Action required")
    : "None";

  const content = `# ${name} — license dossier

_Generated by Perpetua on ${today}._

## 1. Identification

- Product / service: ${name}
- Marketplace / source: ${marketplace(license)}
- Status: ${license.status}
- License key: ${license.license_key}
- Purchase date: ${value(license.purchase_date)}
- Expiry: ${value(license.expiry_date, "Lifetime / none")}
- Product URL: ${value(license.product_url, "—")}
- Redemption URL: ${value(license.redemption_url, "—")}
- Download URL: ${value(license.download_url, "—")}

## 2. Categorization

- Pricing model: lifetime deal (one-time purchase)
- Acquired via: ${marketplace(license)}
- Primary category: _to classify_
- Tags: _add tags_

> What kind of tool is this — e.g. writing, design, SEO, automation, hosting,
> analytics, productivity? Set the primary category and tags above.

## 3. Features & functionality

A complete breakdown should cover:

- Core capabilities — what it does day to day.
- Standout, differentiating features.
- Integrations, imports, and exports.
- Limits of this lifetime tier — seats, usage caps, code stacking.

${value(license.notes, "_No notes captured yet — add what this product does in the license notes._")}

## 4. Best use cases

Who gets the most value, and when:

- Ideal user or role.
- The single job it does best.
- Workflows and stacks it fits into.
- When to reach for a different tool instead.

## Keep-alive & maintenance

- Login cadence: ${keepalive}
- Last used: ${lastUsed}
- Action required: ${action}

---

_Identification and maintenance fields are filled from your Perpetua vault. The
analysis sections (2–4) are a framework to complete: Perpetua is local-first and
does not fetch product data, so it never invents details. A future AI enrichment
can auto-populate these sections._
`;

  return { filename: `${slug}-dossier.md`, content };
}
